apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ include "workbench.redis.namespace" . }}
  labels:
    {{- include "workbench.redis.labels.standard" . | nindent 4 }}
type: Opaque
data:
  workbench.conf: {{ .Files.Get "files/workbench.conf" | b64enc }}
