apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "workbench.redis.namespace" . }}
  labels:
    {{- include "workbench.redis.labels.standard" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "workbench.redis.labels.selector" . | nindent 6 }}
  serviceName: {{ .Values.name | quote }}
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        {{- include "workbench.redis.labels.standard" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Values.name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          command: ["redis-server", "/etc/redis/workbench.conf"]
          ports:
            - containerPort: {{ .Values.service.port }}
              name: redis-port
          volumeMounts:
            - name: {{ .Values.secrets.name }}
              mountPath: /etc/redis
              readOnly: true
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            exec:
              command:
                - redis-cli
                - --user
                - {{ .Values.redisCli.user }}
                - -a
                - {{ .Values.redisCli.password }}
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --user
                - {{ .Values.redisCli.user }}
                - -a
                - {{ .Values.redisCli.password }}
                - ping
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - --user
                - {{ .Values.redisCli.user }}
                - -a
                - {{ .Values.redisCli.password }}
                - ping
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: {{ .Values.secrets.name }}
          secret:
            secretName: {{ .Values.secrets.name }}
