apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "workbench.worker.namespace" . }}
  labels:
    {{- include "workbench.worker.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "workbench.worker.labels.selector" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
