apiVersion: v1
kind: PersistentVolume
metadata:
  name: workbench-rabbitmq-volume
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOncePod
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain # no deletion on PVC deletion
  local:
    path: /mnt/disks/workbench-rabbitmq
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - workbench-0-control-plane
