apiVersion: v1
kind: ResourceQuota
metadata:
  name: workbench-resource-quota
  namespace: workbench-apps
spec:
  hard:
    requests.cpu: "7"
    requests.memory: "10Gi"
    limits.cpu: "7"
    limits.memory: "10Gi"
