workbenchNamespaces:
  - name: workbench-platform
    purpose: platform
  - name: workbench-apps
    purpose: system
  - name: workbench-db
    purpose: database
  - name: workbench-storage
    purpose: storage
  - name: workbench-infra
    purpose: shared-infra

workbenchPartOf: workbench
