apiVersion: v1
kind: Service
metadata:
  name: workbench-postgres-db
spec:
  selector:
    app.kubernetes.io/name: workbench-postgres-db
  ports:
    - name: db-port
      protocol: TCP
      port: 5432
      targetPort: db-port
  type: ClusterIP
  clusterIP: None
