# Used for both:
# - direct: helm upgrade … devops/platform/workbench-namespaces/ -f …/global-values.yaml
# - umbrella: helm upgrade … devops/umbrellas/workbench-umbrella/ -f …/global-values.yaml
#
# All keys live under `global` so Helm propagates them to every subchart’s `.Values.global`.
global:
  imageRegistry: workbenchacr77.azurecr.io
  workbenchPartOf: workbench
  workbenchNamespaces:
    platform:
      name: workbench-platform
      purpose: platform
    apps:
      name: workbench-apps
      purpose: system
    db:
      name: workbench-db
      purpose: database
    storage:
      name: workbench-storage
      purpose: storage
    infra:
      name: workbench-infra
      purpose: shared-infra
  workbenchSecrets:
    apps:
      name: workbench-apps-secrets
  workbenchPki:
    certManagerNamespace: cert-manager
    selfSignedClusterIssuer: workbench-selfsigned-issuer
    rootCaClusterIssuer: workbench-root-ca-issuer
    rootCa:
      certificateName: workbench-root-ca
      secretName: workbench-root-ca-secret
      commonName: workbench-root-ca
      duration: 876000h # 100 years (100 * 365 * 24h)
      renewBefore: 8760h # 1 year before expiry
    intermediateCa:
      certificateName: workbench-intermediate-ca
      secretName: workbench-intermediate-ca-secret
      commonName: workbench-intermediate-ca
      duration: 87600h # 10 years (10 * 365 * 24h)
      renewBefore: 8760h # 1 year before expiry
    caClusterIssuer: workbench-ca-issuer
  workbenchComponents:
    platform:
      name: platform
  workbenchStorageClasses:
    local:
      name: local-storage
    pvc:
      name: standard
  workbenchInfraNode:
    labelKey: workbench.io/infra-node
    labelValue: "true"
  workbenchRabbitMq:
    name: workbench-rabbitmq
    user:
    password:
    uri:
  workbenchRedis:
    name: workbench-redis
    port: 6379
    connectionString:
    user:
    password:
    cluster:
      enabled: false
      replicas: 6
      masters: 3
      replicasPerMaster: 1
  workbenchPostgres:
    connectionString:
    user:
    password:
    database:
