apiVersion: v1
kind: LimitRange
metadata:
  name: workbench-limit-range
  namespace: workbench-apps
spec:
  limits:
    - default:
        cpu: "500m"
      defaultRequest:
        cpu: "50m"
      max:
        cpu: "1"
      type: Container
