apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "workbench.postgres.namespace" . }}
  labels:
    {{- include "workbench.postgres.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "workbench.postgres.labels.selector" . | nindent 4 }}
  ports:
    - name: db-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: db-port
  type: ClusterIP
  clusterIP: None
