apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "workbench.lib.namespace.apps" . }}
  labels:
    {{- include "workbench.lib.labels.standard.apps" . | nindent 4 }}
data:
  ASPNETCORE_URLS: http://+:8080
  AllowedHosts: "*"
  Logging__LogLevel__Default: Information
  Logging__LogLevel__Microsoft.AspNetCore: Warning
  Logging__LogLevel__Microsoft.EntityFrameworkCore: Warning
  Workbench__DurationSecMin: "1"
  Workbench__DurationSecMax: "300"
  Workbench__CpuPercentMin: "0"
  Workbench__CpuPercentMax: "100"
  Workbench__MemoryMbMin: "0"
  Workbench__MemoryMbMax: "1024"
