{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.workbenchSecrets.localCa.name }}
  namespace: {{ .Values.global.workbenchNamespaces.platform.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.workbenchSecrets.localCa.name }}
    app.kubernetes.io/component: {{ .Values.global.workbenchComponents.platform.name }}
    app.kubernetes.io/part-of: {{ .Values.global.workbenchPartOf }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "workbench-local-ca-secret: set tlsCrt (run ./scripts/local-tls-prep.sh)" .Values.tlsCrt | b64enc }}
  tls.key: {{ required "workbench-local-ca-secret: set tlsKey (run ./scripts/local-tls-prep.sh)" .Values.tlsKey | b64enc }}
{{- end }}
