name: workbench-redis
secrets:
  name: workbench-redis-secrets
image:
  repository: redis
  tag: 7-alpine
replicas: 1
revisionHistoryLimit: 3
minReadySeconds: 10
terminationGracePeriodSeconds: 10
service:
  port: 6379
# redisCli user/password: set via global.workbenchRedis in cluster global-values.yaml
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
