apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ include "workbench.api.namespace" . }}
  labels:
    {{- include "workbench.api.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Default: {{ required "workbench-api: set global.workbenchPostgres.connectionString (cluster -f overlay)." .Values.global.workbenchPostgres.connectionString }}
