apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "workbench.lib.namespace.infra" . }}
  labels:
    {{- include "workbench.lib.labels.standard.infra" (dict "ctx" . "component" "broker") | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "workbench.lib.labels.selector.nameOnly" . | nindent 6 }}
  serviceName: {{ .Values.name | quote }}
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        {{- include "workbench.lib.labels.standard.infra" (dict "ctx" . "component" "broker") | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Values.name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.amqpPort }}
              name: rabbitmq-port
            - containerPort: 15672
              name: management-port
          volumeMounts:
            - name: {{ .Values.name }}-volume
              mountPath: /var/lib/rabbitmq
            - name: workbench-rabbitmq-definitions-conf
              mountPath: /etc/rabbitmq/conf.d
              readOnly: true
            - name: workbench-rabbitmq-definitions-json
              mountPath: /etc/rabbitmq/definitions
              readOnly: true
          imagePullPolicy: IfNotPresent
          resources:
            {{- include "workbench.lib.resources.container" .Values.resources | nindent 12 }}
          startupProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            {{- include "workbench.lib.probe.timing" .Values.probes.startup | nindent 12 }}
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            {{- include "workbench.lib.probe.timing" .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            {{- include "workbench.lib.probe.timing" .Values.probes.readiness | nindent 12 }}
      volumes:
        - name: workbench-rabbitmq-definitions-conf
          configMap:
            name: {{ .Values.configMap.name }}
            defaultMode: 420
            items:
              - key: 10-workbench-definitions.conf
                path: 10-workbench-definitions.conf
        - name: workbench-rabbitmq-definitions-json
          configMap:
            name: {{ .Values.configMap.name }}
            defaultMode: 420
            items:
              - key: definitions.json
                path: definitions.json
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.name }}-volume
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: {{ include "workbench.lib.storageClasses.pvcName" . | quote }}
        resources:
          requests:
            storage: {{ .Values.pvc.size }}
