apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.workbenchSecrets.apps.name }}
  namespace: {{ .Values.global.workbenchNamespaces.apps.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.workbenchSecrets.apps.name }}
    app.kubernetes.io/component: {{ .Values.global.workbenchComponents.platform.name }}
    app.kubernetes.io/part-of: {{ .Values.global.workbenchPartOf }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  RabbitMq__Uri: {{ .Values.global.workbenchRabbitMq.uri | b64enc }}
  Redis__ConnectionString: {{ .Values.global.workbenchRedis.connectionString | b64enc }}
