# Apply all Workbench namespaces: kubectl apply --server-side -k devops/k8s/platform/namespaces
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workbench-apps.yaml
  - workbench-db.yaml
  - workbench-storage.yaml
  - workbench-infra.yaml
