apiVersion: v1
kind: Namespace
metadata:
  name: workbench-storage
  labels:
    app.kubernetes.io/name: workbench-storage
    app.kubernetes.io/part-of: workbench
    app.kubernetes.io/managed-by: kustomize
    workbench.io/purpose: storage
