apiVersion: v1
kind: Namespace
metadata:
  name: workbench-apps
  labels:
    app.kubernetes.io/name: workbench-apps
    app.kubernetes.io/part-of: workbench
    app.kubernetes.io/managed-by: kustomize
    workbench.io/purpose: system
