apiVersion: v1
kind: Namespace
metadata:
  name: workbench-infra
  labels:
    app.kubernetes.io/name: workbench-infra
    app.kubernetes.io/part-of: workbench
    app.kubernetes.io/managed-by: kustomize
    workbench.io/purpose: shared-infra
