apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply order intent:
# 1) namespaces + cluster-scoped platform prerequisites
# 2) infra dependencies
# 3) app workloads
resources:
  - platform/namespaces
  - platform/storageclasses
  - platform/secrets
  - platform/policies

  - infra/workbench-postgres-db/base
  - infra/workbench-rabbitmq/base
  - infra/workbench-redis/base

  - apps/workbench-api/overlays/local-kind
  - apps/workbench-worker/overlays/local-kind
  - apps/workbench-jobs/overlays/local-kind
