{{- $workbenchPartOf := .Values.workbenchPartOf -}}
{{- range .Values.workbenchNamespaces }}
{{ include "platform.namespaces.namespace" (
    dict
        "name" .name
        "partOf" $workbenchPartOf
        "purpose" .purpose
        "Release" $.Release
        "Chart" $.Chart
) }}
---
{{ end }}