{{- range $name, $namespace := .Values.namespaces }}
{{ include "platform.namespaces.namespace" (
    dict
        "name" $namespace.name
        "partOf" $.Values.partOf
        "purpose" $namespace.purpose
        "Release" $.Release
        "Chart" $.Chart
) }}
---
{{ end }}