apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "workbench.lib.namespace.apps" . }}
  labels:
    {{- include "workbench.lib.labels.standard.apps" . | nindent 4 }}
data:
  config.js: |
{{- include "workbench.app.config.js" . | nindent 4 }}
