apiVersion: v2
name: workbench-rabbitmq
description: Workbench RabbitMQ StatefulSet and definitions ConfigMap (minimum 1 CPU)
type: application
version: 1.0.0-rc1
appVersion: "1.0.0-rc1"
dependencies:
  - name: workbench-common
    version: 1.0.0-rc1
    repository: file://../../platform/workbench-common
