name: workbench-rabbitmq
configMap:
  name: workbench-rabbitmq-definitions
image:
  repository: rabbitmq
  tag: 4-management-alpine
replicas: 1
revisionHistoryLimit: 3
minReadySeconds: 20
terminationGracePeriodSeconds: 60
service:
  amqpPort: 5672
probes:
  startup:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 30
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  liveness:
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
# RabbitMQ requires at least 1 CPU (request and limit). Do not reduce below 1 CPU.
resources:
  limitsCpu: "1"
  limitsMemory: 512Mi
  requestsCpu: "1"
  requestsMemory: 512Mi
pvc:
  size: 512Mi
pv:
  name: workbench-rabbitmq-volume
  storageClassName: local-storage
  capacity: 512Mi
  path: /mnt/disks/workbench-rabbitmq
