apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - limitranges/workbench-limit-range.yaml
  - resourcequotas/workbench-resource-quota.yaml
  - pdb/workbench-rabbitmq-pdb.yaml
