apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - limit-ranges/workbench-limit-range.yaml
  - resource-quotas/workbench-resource-quota.yaml
  - pod-disruption-budgets/workbench-rabbitmq-pdb.yaml
