apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    {{- include "workbench.postgres.labels.standard" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    - ReadWriteOncePod
  storageClassName: {{ .Values.pv.storageClassName }}
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.pv.path }}
  {{- include "workbench.infraNode.affinity" . | nindent 2 }}
