apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ include "workbench.postgres.namespace" . }}
  labels:
    {{- include "workbench.postgres.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.user }}
  POSTGRES_PASSWORD: {{ .Values.secrets.password }}
  POSTGRES_DB: {{ .Values.secrets.database }}
