apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "workbench.rabbitmq.namespace" . }}
  labels:
    {{- include "workbench.rabbitmq.labels.standard" . | nindent 4 }}
data:
  definitions.json: |
{{ .Files.Get "files/definitions.json" | indent 4 }}
  10-workbench-definitions.conf: |
{{ .Files.Get "files/10-workbench-definitions.conf" | indent 4 }}
